### ISSUE TITLE
Version number mismatch...

### ISSUE THREAD

**Issue by chrismbarr** [d-oliveros/ngSticky#127]
* The [`package.json` file](https://github.com/d-oliveros/ngSticky/blob/master/package.json#L3) says the version is **1.8.7**
* The [`bower.json` file](https://github.com/d-oliveros/ngSticky/blob/master/bower.json#L3) says the version is **1.8.4**
* The [`lib/sticky.js` file](https://github.com/d-oliveros/ngSticky/blob/master/lib/sticky.js#L1) says the version as **1.8.6**

Which one is correct?  I assume the highest version number, but this really creates a lot of confusion! :confused:

**Comment by enkodellc** [comment]
@chrismbarr I have seen similar issues and ended up forking and fixing the issues on my own since @d-oliveros  has not done much with the repo in the last 4/5 months. Someone already as a PR#125  to address this issue. So there is no need for this issue if the PR is merged. 

Unfortunately I have not kept up my branch either. It would be great if others were contributors / owners so that it could be maintained and updated.

**Comment by chrismbarr** [comment]
ok, good to know thanks! I'll close this.
